"""Tests for the golden-display executive OpenPyXL report exporter.

Builds the 4-sheet workbook in memory from the transformed sample datasets,
reloads the generated bytes with openpyxl, and asserts the Phase F (2026-08-25
scope) contract: full-grid left tables (181 / 181 / 813 / 813 rows), unsold
variants rendered as blank C/D with unguarded contribution formulas, always-on
in-bounds ``=SUM`` ranges over every group's span, unguarded E/J formulas that
reproduce the golden workbook's ``#DIV/0!`` cell pattern, the 36-row Produk 2
Group 9 (no double-counting), golden total conservation, right-table
completeness, and number masks.
"""

from __future__ import annotations

import re
from datetime import datetime
from typing import Any, Dict, Sequence

import openpyxl
import pytest
from openpyxl import Workbook
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.domain.catalog import PRODUK_GROUP_ORDER
from app.modules.exporter import (
    ReportSheet,
    UnreportedSheet,
    generate_executive_workbook,
    render_side_by_side_sheet,
    render_unreported_sheet,
)
from app.modules.exporter.styles import (
    FORMAT_CURRENCY_IDR,
    FORMAT_INTEGER,
    FORMAT_PERCENTAGE,
)
from app.modules.ingestion.reader import extract_spreadsheet_rows
from app.modules.profiler.adapters import ShopeeAdapter, TikTokShopAdapter
from app.modules.storage import AnalyticsRepository
from app.modules.storage.database import init_db, session_scope
from app.modules.transformer import (
    PRODUK2_GROUP_ORDER,
    transform_records,
)

PERIOD_START = datetime(2026, 7, 13)
PERIOD_END = datetime(2026, 7, 19, 23, 59, 59)
BATCH_SHOPEE = "SHOPEE-2026-07-13-19"
BATCH_TIKTOK = "TIKTOK-2026-07-13-19"

# Golden totals (from fixtures/golden_totals.json)
GOLDEN_SHOPEE_QTY = 6_910
GOLDEN_SHOPEE_REVENUE = 525_973_986
GOLDEN_TIKTOK_QTY = 11_575
GOLDEN_TIKTOK_REVENUE = 658_458_817
GOLDEN_SHOPEE_GUT = (6_109, 435_136_850)
GOLDEN_TIKTOK_GUT = (10_802, 589_625_412)

_GRID_SIZES = {"produk": 181, "produk2": 813}

_SUM_RE = re.compile(r"^=SUM\(([A-Z])(\d+):([A-Z])(\d+)\)$")
_ANCHOR_RE = re.compile(r"\$H\$(\d+)")


# ---------------------------------------------------------------------------
# Fixtures (mirror test_storage.py: module-scoped StaticPool engine)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def engine():
    eng = create_engine(
        "sqlite://", poolclass=StaticPool, connect_args={"check_same_thread": False}
    )
    init_db(eng)
    yield eng
    eng.dispose()


@pytest.fixture(scope="module")
def factory(engine):
    return sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)


@pytest.fixture(scope="module")
def shopee_result(raw_shopee_path):
    _, raw_rows = extract_spreadsheet_rows(raw_shopee_path)
    return transform_records(ShopeeAdapter().adapt(raw_rows))


@pytest.fixture(scope="module")
def tiktok_result(raw_tts_path):
    _, raw_rows = extract_spreadsheet_rows(raw_tts_path)
    return transform_records(TikTokShopAdapter().adapt(raw_rows))


@pytest.fixture(scope="module")
def persisted(factory, shopee_result, tiktok_result):
    """Persists both reference-period batches once; returns the PersistResults."""
    with session_scope(factory) as session:
        repo = AnalyticsRepository(session)
        shopee = repo.persist_batch(
            BATCH_SHOPEE, "SHOPEE", PERIOD_START, PERIOD_END, shopee_result.records
        )
        tiktok = repo.persist_batch(
            BATCH_TIKTOK,
            "TIKTOK_SHOP",
            PERIOD_START,
            PERIOD_END,
            tiktok_result.records,
        )
    return {"shopee": shopee, "tiktok": tiktok}


@pytest.fixture(scope="module")
def grids():
    from app.modules.transformer import generate_full_produk2_grid, generate_full_produk_grid

    return {
        "produk": generate_full_produk_grid(),
        "produk2": generate_full_produk2_grid(),
    }


@pytest.fixture(scope="module")
def populated(factory, persisted, grids):
    """populate_grid() outputs for all four sheets (real pipeline data)."""
    with session_scope(factory) as session:
        repo = AnalyticsRepository(session)
        return {
            "produk_s": repo.populate_grid(
                BATCH_SHOPEE, is_cross_bundling=0, grid=grids["produk"]
            ),
            "produk_t": repo.populate_grid(
                BATCH_TIKTOK, is_cross_bundling=0, grid=grids["produk"]
            ),
            "produk2_s": repo.populate_grid(
                BATCH_SHOPEE, is_cross_bundling=1, grid=grids["produk2"]
            ),
            "produk2_t": repo.populate_grid(
                BATCH_TIKTOK, is_cross_bundling=1, grid=grids["produk2"]
            ),
        }


@pytest.fixture(scope="module")
def sheet_cases(grids):
    """(title, populated_key, grid, group_order) for all four sheets."""
    return [
        ("Produk S", "produk_s", grids["produk"], PRODUK_GROUP_ORDER),
        ("Produk T", "produk_t", grids["produk"], PRODUK_GROUP_ORDER),
        ("Produk 2 S", "produk2_s", grids["produk2"], PRODUK2_GROUP_ORDER),
        ("Produk 2 T", "produk2_t", grids["produk2"], PRODUK2_GROUP_ORDER),
    ]


@pytest.fixture(scope="module")
def workbook_bytes(populated, sheet_cases):
    sheets = [
        ReportSheet(
            title=title,
            populated=populated[key],
            grid=grid,
            group_order=group_order,
        )
        for title, key, grid, group_order in sheet_cases
    ]
    return generate_executive_workbook(sheets)


@pytest.fixture(scope="module")
def unreported_rows(factory, persisted):
    """Query G outputs for both reference batches (is_reported=0)."""
    with session_scope(factory) as session:
        repo = AnalyticsRepository(session)
        return {
            "s": repo.unreported_analytics(BATCH_SHOPEE),
            "t": repo.unreported_analytics(BATCH_TIKTOK),
        }


@pytest.fixture(scope="module")
def workbook_bytes_with_unreported(populated, sheet_cases, unreported_rows):
    """6-sheet workbook: the four Produk sheets + Tidak Terlaporkan S/T."""
    sheets = [
        ReportSheet(
            title=title,
            populated=populated[key],
            grid=grid,
            group_order=group_order,
        )
        for title, key, grid, group_order in sheet_cases
    ]
    unreported = [
        UnreportedSheet(title="Tidak Terlaporkan S", rows=unreported_rows["s"]),
        UnreportedSheet(title="Tidak Terlaporkan T", rows=unreported_rows["t"]),
    ]
    return generate_executive_workbook(sheets, unreported=unreported)


def _load(workbook_bytes):
    """Reloads the generated workbook bytes (a seekable BytesIO)."""
    workbook_bytes.seek(0)
    return openpyxl.load_workbook(workbook_bytes, data_only=False)


def _cell_int(ws, row: int, col: int) -> int:
    """Reads an integer cell value (non-int cells/empties read as 0)."""
    value = ws.cell(row=row, column=col).value
    return value if isinstance(value, int) else 0


def _emission_rows(grid, group_order):
    """(group, variant) sequence exactly as render_side_by_side_sheet emits.

    Mirrors the renderer's two-loop emission order: for each canonical group,
    every matching catalog grid row.
    """
    rows: list[tuple[str, str]] = []
    for group in group_order:
        group_key = group.rstrip()
        for gr in grid:
            if gr.product_group.rstrip() == group_key:
                rows.append((group_key, gr.clean_variant.rstrip()))
    return rows


def _group_spans(grid, group_order) -> dict[str, tuple[int, int]]:
    """{group: (start_row, end_row)} laid out in the rendered left table."""
    spans: dict[str, list[int]] = {}
    for i, (group, _variant) in enumerate(_emission_rows(grid, group_order)):
        row = 2 + i
        if group not in spans:
            spans[group] = [row, row]
        else:
            spans[group][1] = row
    return {group: tuple(span) for group, span in spans.items()}


def _sold_keys(populated) -> set[tuple[str, str]]:
    """(group, variant) keys that actually sold (qty > 0)."""
    return {
        (row["product_group"].rstrip(), row["clean_variant"].rstrip())
        for row in populated
        if int(row["total_qty"]) > 0
    }


def _group_emitted_sum(ws, group_order, group):
    """Sums the C/D values covered by a populated group's H/I =SUM ranges."""
    summary_row = 2 + group_order.index(group)
    h = ws.cell(row=summary_row, column=8).value
    i = ws.cell(row=summary_row, column=9).value
    m_h = _SUM_RE.match(h)
    m_i = _SUM_RE.match(i)
    assert m_h and m_i, f"expected SUM formulas for {group}, got H={h!r} I={i!r}"
    assert m_h.group(1) == m_h.group(3) == "C"
    assert m_i.group(1) == m_i.group(3) == "D"
    start = int(m_h.group(2))
    end = int(m_h.group(4))
    assert (int(m_i.group(2)), int(m_i.group(4))) == (start, end)
    qty = sum(_cell_int(ws, r, 3) for r in range(start, end + 1))
    rev = sum(_cell_int(ws, r, 4) for r in range(start, end + 1))
    return qty, rev


# ---------------------------------------------------------------------------
# 1. Sheet titles
# ---------------------------------------------------------------------------


def test_sheet_titles(workbook_bytes):
    wb = _load(workbook_bytes)
    assert wb.sheetnames == ["Produk S", "Produk T", "Produk 2 S", "Produk 2 T"]


# ---------------------------------------------------------------------------
# 2. Right-table completeness: every group present in canonical order + TOTAL
# ---------------------------------------------------------------------------


def test_right_table_completeness(workbook_bytes, sheet_cases):
    wb = _load(workbook_bytes)
    for title, _key, _grid, group_order in sheet_cases:
        ws = wb[title]
        groups = [ws.cell(row=r, column=7).value for r in range(2, 2 + len(group_order))]
        assert groups == list(group_order), title
        grand_total_row = 2 + len(group_order)
        assert ws.cell(row=grand_total_row, column=7).value == "TOTAL", title


# ---------------------------------------------------------------------------
# 3. Full-grid left table: every catalog row emitted, nothing spills past
# ---------------------------------------------------------------------------


def test_left_table_full_grid(workbook_bytes, grids, sheet_cases):
    assert len(grids["produk"]) == _GRID_SIZES["produk"]
    assert len(grids["produk2"]) == _GRID_SIZES["produk2"]

    wb = _load(workbook_bytes)
    for title, _key, grid, group_order in sheet_cases:
        ws = wb[title]
        emitted = _emission_rows(grid, group_order)
        assert len(emitted) == len(grid), title
        for i, (group, variant) in enumerate(emitted):
            row = 2 + i
            expected_group = group if (i == 0 or emitted[i - 1][0] != group) else None
            assert ws.cell(row=row, column=1).value == expected_group, (
                f"{title}!A{row}"
            )
            assert ws.cell(row=row, column=2).value == variant, f"{title}!B{row}"
            # E contribution formula present on every left-table row.
            assert isinstance(ws.cell(row=row, column=5).value, str), f"{title}!E{row}"
        # Nothing may spill past the last grid row.
        assert ws.cell(row=2 + len(grid), column=2).value is None, title


# ---------------------------------------------------------------------------
# 4. Unsold variants: blank C/D; sold rows unchanged
# ---------------------------------------------------------------------------


def test_unsold_variants_blank_cd(workbook_bytes, populated, sheet_cases):
    wb = _load(workbook_bytes)
    for title, key, grid, group_order in sheet_cases:
        ws = wb[title]
        sold = _sold_keys(populated[key])
        for i, (group, variant) in enumerate(_emission_rows(grid, group_order)):
            row = 2 + i
            if (group, variant) in sold:
                c = ws.cell(row=row, column=3).value
                d = ws.cell(row=row, column=4).value
                assert isinstance(c, int) and c > 0, f"{title}!C{row}"
                assert isinstance(d, int) and d > 0, f"{title}!D{row}"
            else:
                assert ws.cell(row=row, column=3).value is None, f"{title}!C{row}"
                assert ws.cell(row=row, column=4).value is None, f"{title}!D{row}"


# ---------------------------------------------------------------------------
# 5. Always-on SUM ranges: every group's H/I covers its full contiguous span
# ---------------------------------------------------------------------------


def test_every_group_has_sum_over_span(workbook_bytes, sheet_cases):
    wb = _load(workbook_bytes)
    for title, _key, grid, group_order in sheet_cases:
        ws = wb[title]
        grand_total_row = 2 + len(group_order)
        last_summary_row = grand_total_row - 1
        spans = _group_spans(grid, group_order)
        assert set(spans) == {group.rstrip() for group in group_order}, title

        previous_end: int | None = None
        for group in group_order:
            group_key = group.rstrip()
            summary_row = 2 + group_order.index(group)
            start, end = spans[group_key]
            if previous_end is not None:
                assert start == previous_end + 1, (
                    f"{title} {group_key}: span not contiguous"
                )
            previous_end = end
            assert ws.cell(row=summary_row, column=8).value == f"=SUM(C{start}:C{end})", (
                f"{title}!H{summary_row}"
            )
            assert ws.cell(row=summary_row, column=9).value == f"=SUM(D{start}:D{end})", (
                f"{title}!I{summary_row}"
            )
            assert ws.cell(row=summary_row, column=10).value == (
                f"=(H{summary_row}/$H${grand_total_row})*100%"
            ), f"{title}!J{summary_row}"

        assert ws.cell(row=grand_total_row, column=8).value == (
            f"=SUM(H2:H{last_summary_row})"
        )
        assert ws.cell(row=grand_total_row, column=9).value == (
            f"=SUM(I2:I{last_summary_row})"
        )


# ---------------------------------------------------------------------------
# 6. Zero-total groups: unguarded E formulas (golden #DIV/0! cell pattern)
# ---------------------------------------------------------------------------


def test_zero_total_groups_unguarded_e(workbook_bytes, populated, sheet_cases):
    wb = _load(workbook_bytes)
    for title, key, grid, group_order in sheet_cases:
        ws = wb[title]
        sold_groups = {group for group, _variant in _sold_keys(populated[key])}
        spans = _group_spans(grid, group_order)
        for group in group_order:
            group_key = group.rstrip()
            summary_row = 2 + group_order.index(group)
            h = ws.cell(row=summary_row, column=8).value
            assert isinstance(h, str) and h.startswith("=SUM("), (
                f"{title} {group_key}: H={h!r} must be a SUM formula"
            )
            if group_key in sold_groups:
                continue
            start, end = spans[group_key]
            for r in range(start, end + 1):
                e = ws.cell(row=r, column=5).value
                assert e == f"=(C{r}/$H${summary_row})*100%", (
                    f"{title} {group_key}!E{r}: expected unguarded formula, got {e!r}"
                )


def test_no_baked_div_zero_string(workbook_bytes):
    """No literal `#DIV/0!` value is written; errors are computed on open."""
    wb = _load(workbook_bytes)
    for title in wb.sheetnames:
        ws = wb[title]
        for row in ws.iter_rows():
            for cell in row:
                assert cell.value != "#DIV/0!", f"{title}!{cell.coordinate}"


# ---------------------------------------------------------------------------
# 7. Contribution anchors point at formula cells
# ---------------------------------------------------------------------------


def test_contribution_anchors_target_formula_cells(workbook_bytes, sheet_cases):
    wb = _load(workbook_bytes)
    for title, _key, grid, group_order in sheet_cases:
        ws = wb[title]
        grand_total_row = 2 + len(group_order)

        # E (variant contribution): anchor must be the group's H SUM formula.
        for row in ws.iter_rows(min_col=5, max_col=5):
            cell = row[0]
            value = cell.value
            if not isinstance(value, str) or not value.startswith("=("):
                continue
            anchors = _ANCHOR_RE.findall(value)
            assert len(anchors) == 1, f"{title}!{cell.coordinate}: {value!r}"
            anchor = ws.cell(row=int(anchors[0]), column=8).value
            assert isinstance(anchor, str) and anchor.startswith("=SUM("), (
                f"{title}!{cell.coordinate}: E divisor {anchor!r} is not a formula"
            )

        # J (group contribution): anchor must be the grand-total H formula.
        for row in ws.iter_rows(min_col=10, max_col=10):
            cell = row[0]
            value = cell.value
            if not isinstance(value, str) or not value.startswith("=("):
                continue
            anchors = _ANCHOR_RE.findall(value)
            assert len(anchors) == 1 and int(anchors[0]) == grand_total_row, (
                f"{title}!{cell.coordinate}: {value!r}"
            )
            anchor = ws.cell(row=grand_total_row, column=8).value
            assert isinstance(anchor, str) and anchor.startswith("=SUM(H2:"), (
                f"{title}!{cell.coordinate}: J divisor {anchor!r} is not the grand total"
            )


# ---------------------------------------------------------------------------
# 8. Produk 2 Group 9 is strictly 36 rows (no double-counting overrun)
# ---------------------------------------------------------------------------


def test_produk2_group9_is_36_rows_not_72(grids):
    group9 = PRODUK2_GROUP_ORDER[8]
    full_grid = grids["produk2"]
    g9_rows = [row for row in full_grid if row.product_group.rstrip() == group9]
    assert len(g9_rows) == 36  # Swipe To Glow (6) x The Bloom (6)
    assert len({row.clean_variant for row in g9_rows}) == 36

    synthetic = [
        {
            "product_group": row.product_group,
            "clean_variant": row.clean_variant,
            "total_qty": 1 if row.product_group.rstrip() == group9 else 0,
            "total_revenue": 1_000 if row.product_group.rstrip() == group9 else 0,
        }
        for row in full_grid
    ]

    wb = Workbook()
    ws = wb.active
    assert ws is not None
    ws.title = "Produk 2 S"
    render_side_by_side_sheet(
        ws,
        populated=synthetic,
        grid=full_grid,
        group_order=PRODUK2_GROUP_ORDER,
    )

    spans = _group_spans(full_grid, PRODUK2_GROUP_ORDER)
    start, end = spans[group9]
    assert end - start + 1 == 36

    summary_row = 2 + PRODUK2_GROUP_ORDER.index(group9)
    assert ws.cell(row=summary_row, column=8).value == f"=SUM(C{start}:C{end})"
    assert ws.cell(row=summary_row, column=9).value == f"=SUM(D{start}:D{end})"

    sold_in_span = sum(
        1 for r in range(start, end + 1) if ws.cell(row=r, column=3).value is not None
    )
    assert sold_in_span == 36
    assert ws.cell(row=end + 1, column=3).value is None


# ---------------------------------------------------------------------------
# 9. Golden total conservation through the emitted left table
# ---------------------------------------------------------------------------


def test_golden_totals_conserved(workbook_bytes):
    wb = _load(workbook_bytes)
    ws_s = wb["Produk S"]
    ws_t = wb["Produk T"]

    qty_s = sum(_cell_int(ws_s, r, 3) for r in range(2, ws_s.max_row + 1))
    rev_s = sum(_cell_int(ws_s, r, 4) for r in range(2, ws_s.max_row + 1))
    assert (qty_s, rev_s) == (GOLDEN_SHOPEE_QTY, GOLDEN_SHOPEE_REVENUE)

    qty_t = sum(_cell_int(ws_t, r, 3) for r in range(2, ws_t.max_row + 1))
    rev_t = sum(_cell_int(ws_t, r, 4) for r in range(2, ws_t.max_row + 1))
    assert (qty_t, rev_t) == (GOLDEN_TIKTOK_QTY, GOLDEN_TIKTOK_REVENUE)

    # Glow Up Tint: formula-range sums over the emitted rows match the golden.
    assert _group_emitted_sum(ws_s, PRODUK_GROUP_ORDER, "Glow Up Tint") == GOLDEN_SHOPEE_GUT
    assert _group_emitted_sum(ws_t, PRODUK_GROUP_ORDER, "Glow Up Tint") == GOLDEN_TIKTOK_GUT


# ---------------------------------------------------------------------------
# 10. Number formatting masks applied to all numeric cells
# ---------------------------------------------------------------------------


def test_number_formats(workbook_bytes):
    wb = _load(workbook_bytes)
    ws = wb["Produk S"]

    # Left table: C -> INTEGER, D -> CURRENCY, E -> PERCENTAGE (where present).
    for r in range(2, ws.max_row + 1):
        c = ws.cell(row=r, column=3)
        if c.value is not None:
            assert c.number_format == FORMAT_INTEGER, f"Produk S!C{r}"
        d = ws.cell(row=r, column=4)
        if d.value is not None:
            assert d.number_format == FORMAT_CURRENCY_IDR, f"Produk S!D{r}"
        e = ws.cell(row=r, column=5)
        if e.value is not None:
            assert e.number_format == FORMAT_PERCENTAGE, f"Produk S!E{r}"

    # Right table incl. grand total: H -> INTEGER, I -> CURRENCY, J -> PERCENTAGE.
    for r in range(2, 2 + len(PRODUK_GROUP_ORDER) + 1):
        h = ws.cell(row=r, column=8)
        if h.value is not None:
            assert h.number_format == FORMAT_INTEGER, f"Produk S!H{r}"
        i = ws.cell(row=r, column=9)
        if i.value is not None:
            assert i.number_format == FORMAT_CURRENCY_IDR, f"Produk S!I{r}"
        j = ws.cell(row=r, column=10)
        if j.value is not None:
            assert j.number_format == FORMAT_PERCENTAGE, f"Produk S!J{r}"

    # Spot-check the other three sheets' first summary row.
    for title in ("Produk T", "Produk 2 S", "Produk 2 T"):
        ws2 = wb[title]
        assert ws2.cell(row=2, column=8).number_format == FORMAT_INTEGER
        assert ws2.cell(row=2, column=9).number_format == FORMAT_CURRENCY_IDR
        assert ws2.cell(row=2, column=10).number_format == FORMAT_PERCENTAGE


# ---------------------------------------------------------------------------
# 11. Phase 7: unreported sheets (Tidak Terlaporkan S/T)
# ---------------------------------------------------------------------------


def test_unreported_sheets_render_persisted_entries(workbook_bytes_with_unreported, unreported_rows):
    """The 6-sheet workbook appends Tidak Terlaporkan S/T after the four
    Produk sheets; unreported volume appears only there and matches Query G."""
    wb = _load(workbook_bytes_with_unreported)
    assert wb.sheetnames == [
        "Produk S",
        "Produk T",
        "Produk 2 S",
        "Produk 2 T",
        "Tidak Terlaporkan S",
        "Tidak Terlaporkan T",
    ]

    ws_s = wb["Tidak Terlaporkan S"]
    # 12 distinct Shopee non-catalog listings (13 records, 2 share a key)
    # + TOTAL row.
    assert len(unreported_rows["s"]) == 12
    assert ws_s.max_row == 12 + 1 + 1  # header + data + TOTAL
    for r in range(2, 2 + 12):
        assert ws_s.cell(row=r, column=3).value  # raw variant present
        assert ws_s.cell(row=r, column=4).value == 0
        assert ws_s.cell(row=r, column=5).value == 0
        assert ws_s.cell(row=r, column=4).number_format == FORMAT_INTEGER
        assert ws_s.cell(row=r, column=5).number_format == FORMAT_CURRENCY_IDR
    total_row_s = 2 + 12
    assert ws_s.cell(row=total_row_s, column=1).value == "TOTAL"
    assert ws_s.cell(row=total_row_s, column=4).value == f"=SUM(D2:D{total_row_s - 1})"
    assert ws_s.cell(row=total_row_s, column=5).value == f"=SUM(E2:E{total_row_s - 1})"

    ws_t = wb["Tidak Terlaporkan T"]
    assert len(unreported_rows["t"]) == 1
    # header + 1 data row + TOTAL.
    assert ws_t.max_row == 3
    assert ws_t.cell(row=2, column=1).value == "Tinted Jelly Balm"
    assert ws_t.cell(row=2, column=2).value == "Default"
    assert ws_t.cell(row=2, column=3).value  # raw variant
    assert ws_t.cell(row=2, column=4).value == 1
    assert ws_t.cell(row=2, column=5).value == 22_637
    assert ws_t.cell(row=3, column=1).value == "TOTAL"
    assert ws_t.cell(row=3, column=4).value == "=SUM(D2:D2)"
    assert ws_t.cell(row=3, column=5).value == "=SUM(E2:E2)"


def test_unreported_rows_absent_from_produk_sheets(workbook_bytes_with_unreported):
    """Unreported volume never leaks into the four Produk sheets: TikTok's
    off-grid 'Default' row and Shopee's non-catalog listings are absent."""
    wb = _load(workbook_bytes_with_unreported)
    for title in ("Produk S", "Produk T", "Produk 2 S", "Produk 2 T"):
        ws = wb[title]
        variants = {
            ws.cell(row=r, column=2).value for r in range(2, ws.max_row + 1)
        }
        assert "Default" not in variants, f"{title} leaked off-grid 'Default'"
    # Golden totals conserved through the Produk sheets even with the extra
    # unreported sheets present.
    ws_s = wb["Produk S"]
    ws_t = wb["Produk T"]
    assert (sum(_cell_int(ws_s, r, 3) for r in range(2, ws_s.max_row + 1))) == GOLDEN_SHOPEE_QTY
    assert (sum(_cell_int(ws_t, r, 3) for r in range(2, ws_t.max_row + 1))) == GOLDEN_TIKTOK_QTY


def test_render_unreported_sheet_empty_emits_zero_total():
    """A platform with no unreported rows still emits the sheet with a 0 TOTAL."""
    wb = Workbook()
    ws = wb.active
    assert ws is not None
    render_unreported_sheet(ws, rows=[])
    assert ws.max_row == 2  # header + TOTAL
    assert ws.cell(row=2, column=1).value == "TOTAL"
    assert ws.cell(row=2, column=4).value == 0
    assert ws.cell(row=2, column=5).value == 0
