"""Tests for the Phase 5 executive OpenPyXL report exporter.

Builds the 4-sheet workbook in memory from the transformed sample datasets,
reloads the generated bytes with openpyxl, and asserts the plan's verification
bullets: sheet titles, complete right tables, the Empty-Group Rule (literal 0,
never ``=SUM`` over an absent range), ``Bundling Tinted Jelly Balm`` presence,
in-bounds dynamic formulas, the 36-row Produk 2 Group 9 (no double-counting),
zero ``#DIV/0!`` risk, golden total conservation, and number masks.
"""

from __future__ import annotations

import re
from datetime import datetime
from typing import Any, Dict, Sequence

import openpyxl
import pytest
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.domain.catalog import PRODUK_GROUP_ORDER
from app.modules.exporter import (
    ReportSheet,
    generate_executive_workbook,
    render_side_by_side_sheet,
)
from app.modules.exporter.styles import (
    FORMAT_CURRENCY_IDR,
    FORMAT_INTEGER,
    FORMAT_PERCENTAGE,
)
from app.modules.ingestion.reader import extract_spreadsheet_rows
from app.modules.profiler.adapters import ShopeeAdapter, TikTokShopAdapter
from app.modules.storage import AnalyticsRepository
from app.modules.storage.database import init_db, session_scope
from app.modules.transformer import (
    PRODUK2_GROUP_ORDER,
    generate_full_produk2_grid,
    generate_full_produk_grid,
    transform_records,
)

PERIOD_START = datetime(2026, 7, 13)
PERIOD_END = datetime(2026, 7, 19, 23, 59, 59)
BATCH_SHOPEE = "SHOPEE-2026-07-13-19"
BATCH_TIKTOK = "TIKTOK-2026-07-13-19"

# Golden totals (from fixtures/golden_totals.json)
GOLDEN_SHOPEE_QTY = 6_910
GOLDEN_SHOPEE_REVENUE = 525_973_986
GOLDEN_TIKTOK_QTY = 11_575
GOLDEN_TIKTOK_REVENUE = 658_458_817
GOLDEN_SHOPEE_GUT = (6_109, 435_136_850)
GOLDEN_TIKTOK_GUT = (10_802, 589_625_412)

TJB_BUNDLE_GROUP = "Bundling Tinted Jelly Balm"

SHEET_CASES = [
    ("Produk S", PRODUK_GROUP_ORDER),
    ("Produk T", PRODUK_GROUP_ORDER),
    ("Produk 2 S", PRODUK2_GROUP_ORDER),
    ("Produk 2 T", PRODUK2_GROUP_ORDER),
]

_SUM_RE = re.compile(r"^=SUM\(([A-Z])(\d+):([A-Z])(\d+)\)$")
_ANCHOR_RE = re.compile(r"\$H\$(\d+)")


# ---------------------------------------------------------------------------
# Fixtures (mirror test_storage.py: module-scoped StaticPool engine)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def engine():
    eng = create_engine(
        "sqlite://", poolclass=StaticPool, connect_args={"check_same_thread": False}
    )
    init_db(eng)
    yield eng
    eng.dispose()


@pytest.fixture(scope="module")
def factory(engine):
    return sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)


@pytest.fixture(scope="module")
def shopee_result(raw_shopee_path):
    _, raw_rows = extract_spreadsheet_rows(raw_shopee_path)
    return transform_records(ShopeeAdapter().adapt(raw_rows))


@pytest.fixture(scope="module")
def tiktok_result(raw_tts_path):
    _, raw_rows = extract_spreadsheet_rows(raw_tts_path)
    return transform_records(TikTokShopAdapter().adapt(raw_rows))


@pytest.fixture(scope="module")
def persisted(factory, shopee_result, tiktok_result):
    """Persists both reference-period batches once; returns the PersistResults."""
    with session_scope(factory) as session:
        repo = AnalyticsRepository(session)
        shopee = repo.persist_batch(
            BATCH_SHOPEE, "SHOPEE", PERIOD_START, PERIOD_END, shopee_result.records
        )
        tiktok = repo.persist_batch(
            BATCH_TIKTOK,
            "TIKTOK_SHOP",
            PERIOD_START,
            PERIOD_END,
            tiktok_result.records,
        )
    return {"shopee": shopee, "tiktok": tiktok}


@pytest.fixture(scope="module")
def grids():
    return {
        "produk": generate_full_produk_grid(),
        "produk2": generate_full_produk2_grid(),
    }


@pytest.fixture(scope="module")
def populated(factory, persisted, grids):
    """populate_grid() outputs for all four sheets (real pipeline data)."""
    with session_scope(factory) as session:
        repo = AnalyticsRepository(session)
        return {
            "produk_s": repo.populate_grid(
                BATCH_SHOPEE, is_cross_bundling=0, grid=grids["produk"]
            ),
            "produk_t": repo.populate_grid(
                BATCH_TIKTOK, is_cross_bundling=0, grid=grids["produk"]
            ),
            "produk2_s": repo.populate_grid(
                BATCH_SHOPEE, is_cross_bundling=1, grid=grids["produk2"]
            ),
            "produk2_t": repo.populate_grid(
                BATCH_TIKTOK, is_cross_bundling=1, grid=grids["produk2"]
            ),
        }


@pytest.fixture(scope="module")
def workbook_bytes(populated, grids):
    sheets = [
        ReportSheet(
            title="Produk S",
            populated=populated["produk_s"],
            grid=grids["produk"],
            group_order=PRODUK_GROUP_ORDER,
        ),
        ReportSheet(
            title="Produk T",
            populated=populated["produk_t"],
            grid=grids["produk"],
            group_order=PRODUK_GROUP_ORDER,
        ),
        ReportSheet(
            title="Produk 2 S",
            populated=populated["produk2_s"],
            grid=grids["produk2"],
            group_order=PRODUK2_GROUP_ORDER,
        ),
        ReportSheet(
            title="Produk 2 T",
            populated=populated["produk2_t"],
            grid=grids["produk2"],
            group_order=PRODUK2_GROUP_ORDER,
        ),
    ]
    return generate_executive_workbook(sheets)


def _load(workbook_bytes):
    """Reloads the generated workbook bytes (a seekable BytesIO)."""
    workbook_bytes.seek(0)
    return openpyxl.load_workbook(workbook_bytes, data_only=False)


def _populated_by_title(populated: Dict[str, Sequence[Dict[str, Any]]], title: str):
    key = {
        "Produk S": "produk_s",
        "Produk T": "produk_t",
        "Produk 2 S": "produk2_s",
        "Produk 2 T": "produk2_t",
    }[title]
    return populated[key]


def _cell_int(ws, row: int, col: int) -> int:
    """Reads an integer cell value (non-int cells/empties read as 0)."""
    value = ws.cell(row=row, column=col).value
    return value if isinstance(value, int) else 0


def _group_emitted_sum(ws, group_order, group):
    """Sums the C/D values covered by a populated group's H/I =SUM ranges."""
    summary_row = 2 + group_order.index(group)
    h = ws.cell(row=summary_row, column=8).value
    i = ws.cell(row=summary_row, column=9).value
    m_h = _SUM_RE.match(h)
    m_i = _SUM_RE.match(i)
    assert m_h and m_i, f"expected SUM formulas for {group}, got H={h!r} I={i!r}"
    assert m_h.group(1) == m_h.group(3) == "C"
    assert m_i.group(1) == m_i.group(3) == "D"
    start = int(m_h.group(2))
    end = int(m_h.group(4))
    assert (int(m_i.group(2)), int(m_i.group(4))) == (start, end)
    qty = sum(_cell_int(ws, r, 3) for r in range(start, end + 1))
    rev = sum(_cell_int(ws, r, 4) for r in range(start, end + 1))
    return qty, rev


# ---------------------------------------------------------------------------
# 1. Sheet titles
# ---------------------------------------------------------------------------


def test_sheet_titles(workbook_bytes):
    wb = _load(workbook_bytes)
    assert wb.sheetnames == ["Produk S", "Produk T", "Produk 2 S", "Produk 2 T"]


# ---------------------------------------------------------------------------
# 2. Right-table completeness: every group present in canonical order + TOTAL
# ---------------------------------------------------------------------------


def test_right_table_completeness(workbook_bytes):
    wb = _load(workbook_bytes)
    for title, group_order in SHEET_CASES:
        ws = wb[title]
        groups = [ws.cell(row=r, column=7).value for r in range(2, 2 + len(group_order))]
        assert groups == list(group_order), title
        grand_total_row = 2 + len(group_order)
        assert ws.cell(row=grand_total_row, column=7).value == "TOTAL", title


# ---------------------------------------------------------------------------
# 3. Empty-Group Rule: literal 0, never =SUM() over an absent range
# ---------------------------------------------------------------------------


def test_empty_groups_have_literal_zero(workbook_bytes, populated):
    wb = _load(workbook_bytes)
    for title, group_order in SHEET_CASES:
        ws = wb[title]
        emitted = {
            row["product_group"].rstrip()
            for row in _populated_by_title(populated, title)
            if int(row["total_qty"]) > 0
        }
        for idx, group in enumerate(group_order):
            if group in emitted:
                continue
            summary_row = 2 + idx
            h = ws.cell(row=summary_row, column=8).value
            i = ws.cell(row=summary_row, column=9).value
            assert h == 0 and isinstance(h, int) and not isinstance(h, bool), (
                f"{title} {group}: H={h!r} must be literal int 0"
            )
            assert i == 0 and isinstance(i, int) and not isinstance(i, bool), (
                f"{title} {group}: I={i!r} must be literal int 0"
            )


def test_no_sum_formula_on_empty_groups(workbook_bytes, populated):
    wb = _load(workbook_bytes)
    for title, group_order in SHEET_CASES:
        ws = wb[title]
        emitted = {
            row["product_group"].rstrip()
            for row in _populated_by_title(populated, title)
            if int(row["total_qty"]) > 0
        }
        for idx, group in enumerate(group_order):
            if group in emitted:
                continue
            summary_row = 2 + idx
            assert not str(ws.cell(row=summary_row, column=8).value).startswith("=SUM")
            assert not str(ws.cell(row=summary_row, column=9).value).startswith("=SUM")


# ---------------------------------------------------------------------------
# 4. Bundling Tinted Jelly Balm present with literal 0 on Produk S and T
# ---------------------------------------------------------------------------


def test_bundling_tjb_zero_present(workbook_bytes):
    wb = _load(workbook_bytes)
    for title in ("Produk S", "Produk T"):
        ws = wb[title]
        summary_row = 2 + PRODUK_GROUP_ORDER.index(TJB_BUNDLE_GROUP)
        assert ws.cell(row=summary_row, column=7).value == TJB_BUNDLE_GROUP
        assert ws.cell(row=summary_row, column=8).value == 0
        assert ws.cell(row=summary_row, column=9).value == 0


# ---------------------------------------------------------------------------
# 5. Dynamic formulas reference valid, in-bounds row ranges
# ---------------------------------------------------------------------------


def test_formula_ranges_in_bounds(workbook_bytes):
    wb = _load(workbook_bytes)
    for title, group_order in SHEET_CASES:
        ws = wb[title]
        grand_total_row = 2 + len(group_order)
        last_summary_row = grand_total_row - 1

        # Left-table extent = last row carrying a value in cols A-E.
        max_left_row: int = 1
        for row in ws.iter_rows(min_col=1, max_col=5):
            if any(cell.value is not None for cell in row):
                max_left_row = max(max_left_row, row[0].row or 0)

        for row in ws.iter_rows():
            for cell in row:
                value = cell.value
                if not isinstance(value, str) or not value.startswith("="):
                    continue
                if value.startswith("=SUM("):
                    m = _SUM_RE.match(value)
                    assert m, f"{title}!{cell.coordinate}: malformed SUM {value!r}"
                    col1, r1, col2, r2 = m.group(1), int(m.group(2)), m.group(3), int(m.group(4))
                    assert col1 == col2, f"{title}!{cell.coordinate}: mixed columns {value!r}"
                    if cell.column in (8, 9) and cell.row == grand_total_row:
                        # Grand-total SUM ranges cover the summary rows only.
                        assert (col1, r1, r2) == (get_column_letter(cell.column), 2, last_summary_row), (
                            f"{title}!{cell.coordinate}: {value!r}"
                        )
                    else:
                        # Group SUM ranges must lie inside the emitted left table.
                        assert 2 <= r1 <= r2 <= max_left_row, (
                            f"{title}!{cell.coordinate}: out-of-bounds {value!r}"
                        )
                for anchor in _ANCHOR_RE.findall(value):
                    assert 2 <= int(anchor) <= grand_total_row, (
                        f"{title}!{cell.coordinate}: anchor out of bounds {value!r}"
                    )


# ---------------------------------------------------------------------------
# 6. Produk 2 Group 9 is strictly 36 rows (no double-counting overrun)
# ---------------------------------------------------------------------------


def test_produk2_group9_is_36_rows_not_72():
    grid9 = [
        row
        for row in generate_full_produk2_grid()
        if row.product_group.rstrip() == PRODUK2_GROUP_ORDER[8]
    ]
    assert len(grid9) == 36  # Swipe To Glow (6) x The Bloom (6)

    synthetic = [
        {
            "product_group": row.product_group,
            "clean_variant": row.clean_variant,
            "total_qty": 1,
            "total_revenue": 1_000,
        }
        for row in grid9
    ]

    wb = Workbook()
    ws = wb.active
    assert ws is not None
    ws.title = "Produk 2 S"
    render_side_by_side_sheet(
        ws,
        populated=synthetic,
        grid=grid9,
        group_order=PRODUK2_GROUP_ORDER,
    )

    emitted = sum(
        1
        for r in range(2, 2 + len(grid9))
        if ws.cell(row=r, column=3).value is not None
    )
    assert emitted == 36
    # Nothing may spill past the 36 rows.
    assert ws.cell(row=2 + len(grid9), column=3).value is None

    # Group 9's summary H formula covers exactly C2:C37 (36 rows, not 72).
    summary_row = 2 + PRODUK2_GROUP_ORDER.index(PRODUK2_GROUP_ORDER[8])
    assert ws.cell(row=summary_row, column=8).value == "=SUM(C2:C37)"
    assert ws.cell(row=summary_row, column=9).value == "=SUM(D2:D37)"

    # Every other group stays empty -> literal 0 on the right table.
    assert ws.cell(row=2, column=8).value == 0
    assert ws.cell(row=2, column=9).value == 0


# ---------------------------------------------------------------------------
# 7. No #DIV/0!; contribution anchors point at formula cells
# ---------------------------------------------------------------------------


def test_no_div_zero_anywhere(workbook_bytes):
    wb = _load(workbook_bytes)
    for title in wb.sheetnames:
        ws = wb[title]
        for row in ws.iter_rows():
            for cell in row:
                assert cell.value != "#DIV/0!", f"{title}!{cell.coordinate}"
                if isinstance(cell.value, str):
                    assert "#DIV/0!" not in cell.value, f"{title}!{cell.coordinate}"


def test_contribution_anchors_target_formula_cells(workbook_bytes):
    wb = _load(workbook_bytes)
    for title, group_order in SHEET_CASES:
        ws = wb[title]
        grand_total_row = 2 + len(group_order)

        # E (variant contribution): anchor must be the group's H SUM formula.
        for row in ws.iter_rows(min_col=5, max_col=5):
            cell = row[0]
            value = cell.value
            if not isinstance(value, str) or not value.startswith("=("):
                continue
            anchors = _ANCHOR_RE.findall(value)
            assert len(anchors) == 1, f"{title}!{cell.coordinate}: {value!r}"
            anchor = ws.cell(row=int(anchors[0]), column=8).value
            assert isinstance(anchor, str) and anchor.startswith("=SUM("), (
                f"{title}!{cell.coordinate}: E divisor {anchor!r} is not a formula"
            )

        # J (group contribution): anchor must be the grand-total H formula.
        for row in ws.iter_rows(min_col=10, max_col=10):
            cell = row[0]
            value = cell.value
            if not isinstance(value, str) or not value.startswith("=("):
                continue
            anchors = _ANCHOR_RE.findall(value)
            assert len(anchors) == 1 and int(anchors[0]) == grand_total_row, (
                f"{title}!{cell.coordinate}: {value!r}"
            )
            anchor = ws.cell(row=grand_total_row, column=8).value
            assert isinstance(anchor, str) and anchor.startswith("=SUM(H2:"), (
                f"{title}!{cell.coordinate}: J divisor {anchor!r} is not the grand total"
            )


# ---------------------------------------------------------------------------
# 8. Golden total conservation through the emitted left table
# ---------------------------------------------------------------------------


def test_golden_totals_conserved(workbook_bytes):
    wb = _load(workbook_bytes)
    ws_s = wb["Produk S"]
    ws_t = wb["Produk T"]

    qty_s = sum(_cell_int(ws_s, r, 3) for r in range(2, ws_s.max_row + 1))
    rev_s = sum(_cell_int(ws_s, r, 4) for r in range(2, ws_s.max_row + 1))
    assert (qty_s, rev_s) == (GOLDEN_SHOPEE_QTY, GOLDEN_SHOPEE_REVENUE)

    qty_t = sum(_cell_int(ws_t, r, 3) for r in range(2, ws_t.max_row + 1))
    rev_t = sum(_cell_int(ws_t, r, 4) for r in range(2, ws_t.max_row + 1))
    assert (qty_t, rev_t) == (GOLDEN_TIKTOK_QTY, GOLDEN_TIKTOK_REVENUE)

    # Glow Up Tint: formula-range sums over the emitted rows match the golden.
    assert _group_emitted_sum(ws_s, PRODUK_GROUP_ORDER, "Glow Up Tint") == GOLDEN_SHOPEE_GUT
    assert _group_emitted_sum(ws_t, PRODUK_GROUP_ORDER, "Glow Up Tint") == GOLDEN_TIKTOK_GUT


# ---------------------------------------------------------------------------
# 9. Number formatting masks applied to all numeric cells
# ---------------------------------------------------------------------------


def test_number_formats(workbook_bytes):
    wb = _load(workbook_bytes)
    ws = wb["Produk S"]

    # Left table: C -> INTEGER, D -> CURRENCY, E -> PERCENTAGE (where present).
    for r in range(2, ws.max_row + 1):
        c = ws.cell(row=r, column=3)
        if c.value is not None:
            assert c.number_format == FORMAT_INTEGER, f"Produk S!C{r}"
        d = ws.cell(row=r, column=4)
        if d.value is not None:
            assert d.number_format == FORMAT_CURRENCY_IDR, f"Produk S!D{r}"
        e = ws.cell(row=r, column=5)
        if e.value is not None:
            assert e.number_format == FORMAT_PERCENTAGE, f"Produk S!E{r}"

    # Right table incl. grand total: H -> INTEGER, I -> CURRENCY, J -> PERCENTAGE.
    for r in range(2, 2 + len(PRODUK_GROUP_ORDER) + 1):
        h = ws.cell(row=r, column=8)
        if h.value is not None:
            assert h.number_format == FORMAT_INTEGER, f"Produk S!H{r}"
        i = ws.cell(row=r, column=9)
        if i.value is not None:
            assert i.number_format == FORMAT_CURRENCY_IDR, f"Produk S!I{r}"
        j = ws.cell(row=r, column=10)
        if j.value is not None:
            assert j.number_format == FORMAT_PERCENTAGE, f"Produk S!J{r}"

    # Spot-check the other three sheets' first summary row.
    for title in ("Produk T", "Produk 2 S", "Produk 2 T"):
        ws2 = wb[title]
        assert ws2.cell(row=2, column=8).number_format == FORMAT_INTEGER
        assert ws2.cell(row=2, column=9).number_format == FORMAT_CURRENCY_IDR
        assert ws2.cell(row=2, column=10).number_format == FORMAT_PERCENTAGE
