/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Spreadsheet
         * @description Uploads a spreadsheet and returns structural metadata plus sample rows.
         */
        post: operations["ingest_spreadsheet_api_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Profile Spreadsheet
         * @description Detects the platform adapter or returns a cached mapping template.
         */
        post: operations["profile_spreadsheet_api_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transform And Save
         * @description Runs the ELT pipeline, persists the batch, and returns its summary.
         *
         *     ``parent_row_rule`` is advisory metadata stored in the mapping template;
         *     parent-row elimination is performed by the platform adapter and the
         *     ``persist_batch`` scope boundary (never a raw pre-filter).
         */
        post: operations["transform_and_save_api_transform_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Batches
         * @description Lists all persisted batches, newest first.
         */
        get: operations["list_batches_api_reports_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/batches/{batch_id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch Variants
         * @description Returns variant-level performance breakdown for a batch.
         *
         *     ``isBundling`` (0 = Single, 1 = Bundling, omitted = both) narrows the
         *     reported subset alongside ``is_cross_bundling``.
         */
        get: operations["batch_variants_api_reports_batches__batch_id__variants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/batches/{batch_id}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch Products
         * @description Returns master product group rollups for a batch.
         *
         *     ``isBundling`` (0 = Single, 1 = Bundling, omitted = both) narrows the
         *     reported subset alongside ``is_cross_bundling``.
         */
        get: operations["batch_products_api_reports_batches__batch_id__products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/batches/{batch_id}/unreported": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch Unreported
         * @description Query G: persisted non-reportable entries for a batch.
         *
         *     ``is_reported = 0`` rows only (off-grid variants like standalone
         *     'tidak boleh ecer' / 'free gift', and non-catalog product groups). Never
         *     appears in report queries or the four Produk sheets.
         */
        get: operations["batch_unreported_api_reports_batches__batch_id__unreported_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/aggregate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate Reports
         * @description Query C: cross-batch aggregation across platforms with optional filters.
         *
         *     ``platform`` / ``periodStart`` / ``periodEnd`` / ``isCrossBundling`` are
         *     all optional camelCase query parameters (R9 bound coercion already lives in
         *     ``AnalyticsRepository.multi_platform_aggregation``).
         */
        get: operations["aggregate_reports_api_reports_aggregate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Batch
         * @description Deletes a batch (idempotent: missing batches delete zero rows).
         */
        delete: operations["delete_batch_api_reports_batches__batch_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Excel
         * @description Streams a 4-sheet executive workbook for the selected batches.
         *
         *     Exactly one batch per platform is required; sheets are emitted in
         *     canonical order ``Produk S, Produk T, Produk 2 S, Produk 2 T``.
         */
        get: operations["export_excel_api_export_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AggregateRowDTO
         * @description Multi-batch / multi-platform / date-range aggregation row (Query C).
         *
         *     Groups by (platform, product_group, clean_variant) across every persisted
         *     batch matching the optional platform / period / cross-bundling filters;
         *     ``contribution_ratio`` is the 0-1 unit share against the filtered grand
         *     total quantity.
         */
        AggregateRowDTO: {
            /** Platform */
            platform: string;
            /** Productgroup */
            productGroup: string;
            /** Cleanvariant */
            cleanVariant: string;
            /** Totalqty */
            totalQty: number;
            /** Totalrevenue */
            totalRevenue: number;
            /** Contributionratio */
            contributionRatio: number;
        };
        /**
         * BatchSummaryDTO
         * @description Storage-level batch summary row (Query D raw transaction sums).
         *
         *     ``total_products`` / ``grand_total_*`` are whole-batch figures including
         *     cross-bundling rows; they are NOT the workbook (grid-intersected) totals.
         */
        BatchSummaryDTO: {
            /** Importbatchid */
            importBatchId: string;
            /** Platform */
            platform: string;
            /** Periodstart */
            periodStart?: string | null;
            /** Periodend */
            periodEnd?: string | null;
            /** Createdat */
            createdAt?: string | null;
            /** Totalproducts */
            totalProducts: number;
            /** Grandtotalqty */
            grandTotalQty: number;
            /** Grandtotalrevenue */
            grandTotalRevenue: number;
        };
        /** Body_ingest_spreadsheet_api_ingest_post */
        Body_ingest_spreadsheet_api_ingest_post: {
            /** File */
            file: string;
        };
        /**
         * CleaningRuleDTO
         * @description Deterministic regex cleaning rule.
         */
        CleaningRuleDTO: {
            /** Pattern */
            pattern: string;
            /**
             * Replacement
             * @default
             */
            replacement: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * ColumnMappingDTO
         * @description Mapping from canonical field names to raw spreadsheet column headers.
         */
        ColumnMappingDTO: {
            /** Productgroup */
            productGroup: string;
            /** Rawvariant */
            rawVariant: string;
            /** Qtysold */
            qtySold: string;
            /** Revenue */
            revenue: string;
            /** Sku */
            sku?: string | null;
            /** Casecolor */
            caseColor?: string | null;
        };
        /**
         * DeleteBatchResponseDTO
         * @description Outcome of batch deletion.
         */
        DeleteBatchResponseDTO: {
            /** Success */
            success: boolean;
            /** Deletedcount */
            deletedCount: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionResultDTO
         * @description Result of uploading and structurally inspecting a spreadsheet.
         */
        IngestionResultDTO: {
            /** Fileid */
            fileId: string;
            /** Filename */
            fileName: string;
            /** Filesizebytes */
            fileSizeBytes: number;
            /** Detecteddelimiter */
            detectedDelimiter?: string | null;
            /** Availablesheets */
            availableSheets?: string[];
            /** Activesheet */
            activeSheet: string;
            /** Totalrows */
            totalRows: number;
            /** Rawheaders */
            rawHeaders?: string[];
            /** Samplerows */
            sampleRows?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ParentRowIgnoreCondition
         * @description Conditions under which a parent/summary row must be pruned.
         * @enum {string}
         */
        ParentRowIgnoreCondition: "EQUALS_DASH" | "IS_EMPTY" | "CONTAINS_TOTAL";
        /**
         * ParentRowRuleDTO
         * @description Rule identifying parent/summary rows to prune.
         */
        ParentRowRuleDTO: {
            /** Targetcolumn */
            targetColumn: string;
            ignoreCondition: components["schemas"]["ParentRowIgnoreCondition"];
        };
        /**
         * ProductSummaryDTO
         * @description Master product group rollup (report Table 2).
         */
        ProductSummaryDTO: {
            /** Productgroup */
            productGroup: string;
            /** Totalqty */
            totalQty: number;
            /** Totalrevenue */
            totalRevenue: number;
            /** Contributionratio */
            contributionRatio: number;
        };
        /**
         * ProfileRequestDTO
         * @description Body for the profile endpoint.
         */
        ProfileRequestDTO: {
            /** Fileid */
            fileId: string;
            /** Activesheet */
            activeSheet?: string | null;
        };
        /**
         * ProfilerResponseDTO
         * @description Platform detection outcome for a header signature.
         */
        ProfilerResponseDTO: {
            /** Iscached */
            isCached: boolean;
            /** Platform */
            platform: string;
            /** Confidence */
            confidence: number;
            columnMapping: components["schemas"]["ColumnMappingDTO"];
            parentRowRule?: components["schemas"]["ParentRowRuleDTO"] | null;
            /** Suggestedcleaningrules */
            suggestedCleaningRules?: components["schemas"]["CleaningRuleDTO"][];
        };
        /**
         * TransformAndSaveRequestDTO
         * @description Body for the transform-and-save pipeline.
         *
         *     ``period_start`` / ``period_end`` are optional ISO dates supplied by the
         *     user; the route expands them to day-bounded datetimes for persistence.
         */
        TransformAndSaveRequestDTO: {
            /** Fileid */
            fileId: string;
            /** Activesheet */
            activeSheet?: string | null;
            /** Platform */
            platform: string;
            /** Periodstart */
            periodStart?: string | null;
            /** Periodend */
            periodEnd?: string | null;
            columnMapping: components["schemas"]["ColumnMappingDTO"];
            parentRowRule?: components["schemas"]["ParentRowRuleDTO"] | null;
            /** Cleaningrules */
            cleaningRules?: components["schemas"]["CleaningRuleDTO"][];
            /**
             * Saveastemplate
             * @default true
             */
            saveAsTemplate: boolean;
        };
        /**
         * TransformResponseDTO
         * @description Report-boundary batch summary plus persistence audit details.
         *
         *     ``reported_*`` mirrors the Produk workbook (grid-intersected,
         *     ``is_reported = 1``), distinct from the storage-level ``grandTotal*``
         *     figures on ``/reports/batches`` (R5). ``skipped_*`` is now the dash-only
         *     excluded tally (parent summaries). ``unreported_*`` is the persisted
         *     non-reportable volume (off-grid variants, non-catalog products) -- stored
         *     and viewable via ``/unreported`` but never part of a report figure.
         */
        TransformResponseDTO: {
            /** Importbatchid */
            importBatchId: string;
            /** Platform */
            platform: string;
            /** Periodstart */
            periodStart?: string | null;
            /** Periodend */
            periodEnd?: string | null;
            /** Createdat */
            createdAt?: string | null;
            /** Reportedproductcount */
            reportedProductCount: number;
            /** Reportedtotalqty */
            reportedTotalQty: number;
            /** Reportedtotalrevenue */
            reportedTotalRevenue: number;
            /** Insertedcount */
            insertedCount: number;
            /** Skippedcount */
            skippedCount: number;
            /** Skippedqty */
            skippedQty: number;
            /** Skippedrevenue */
            skippedRevenue: number;
            /** Unreportedcount */
            unreportedCount: number;
            /** Unreportedqty */
            unreportedQty: number;
            /** Unreportedrevenue */
            unreportedRevenue: number;
            /** Warningcount */
            warningCount: number;
        };
        /**
         * UnreportedVariantDTO
         * @description Persisted non-reportable entry (Query G, ``is_reported == 0``).
         *
         *     Covers off-grid variants (standalone 'tidak boleh ecer', 'free gift',
         *     etc.) and non-catalog product groups. Stored for traceability and shown on
         *     the dashboard / 'Tidak Terlaporkan S/T' export sheets; never appears in a
         *     report query or the four Produk sheets. ``raw_variant`` carries the full
         *     original variant label and ``raw_product`` the verbatim source product
         *     column value for provenance.
         */
        UnreportedVariantDTO: {
            /** Productgroup */
            productGroup: string;
            /** Cleanvariant */
            cleanVariant: string;
            /** Rawvariant */
            rawVariant: string;
            /** Rawproduct */
            rawProduct?: string | null;
            /** Totalqty */
            totalQty: number;
            /** Totalrevenue */
            totalRevenue: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VariantPerformanceDTO
         * @description Variant-level performance row (report Table 1).
         */
        VariantPerformanceDTO: {
            /** Productgroup */
            productGroup: string;
            /** Cleanvariant */
            cleanVariant: string;
            /** Isbundling */
            isBundling: boolean;
            /** Iscrossbundling */
            isCrossBundling: boolean;
            /** Totalqty */
            totalQty: number;
            /** Totalrevenue */
            totalRevenue: number;
            /** Contributionratio */
            contributionRatio: number;
            /** Casecolor */
            caseColor?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ingest_spreadsheet_api_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_spreadsheet_api_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResultDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_spreadsheet_api_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilerResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transform_and_save_api_transform_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransformAndSaveRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransformResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_reports_batches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchSummaryDTO"][];
                };
            };
        };
    };
    batch_variants_api_reports_batches__batch_id__variants_get: {
        parameters: {
            query?: {
                is_cross_bundling?: number;
                isBundling?: number | null;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantPerformanceDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_products_api_reports_batches__batch_id__products_get: {
        parameters: {
            query?: {
                is_cross_bundling?: number;
                isBundling?: number | null;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSummaryDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_unreported_api_reports_batches__batch_id__unreported_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreportedVariantDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aggregate_reports_api_reports_aggregate_get: {
        parameters: {
            query?: {
                platform?: string | null;
                periodStart?: string | null;
                periodEnd?: string | null;
                isCrossBundling?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregateRowDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_batch_api_reports_batches__batch_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteBatchResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_excel_api_export_excel_get: {
        parameters: {
            query?: {
                batchIds?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
